version: '3'

services:
  greeter_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    networks:
      - helloworld
  greeter_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - greeter_server
    networks:
      - helloworld
networks:
  helloworld:
